### ISSUE TITLE
Unintended Consequences

### ISSUE THREAD

**Issue by dhruvdhody** [intarchboard/workshop-m-ten#10]
One takeaway from the workshop for me was that we need to think more deeply about the unintended consequences of our work such as how it impacts other network deployments (such as managed private networks). 

I want to check if this should be spelt out explicitly, we do have some text that mentions this as an example but should we go further? Thoughts?

**Comment by mirjak** [comment]
I guess we could add something to the confusion discussion. Do you want to propose some text? That usually easier to have a discussion.

**Comment by hardaker** [comment]
mirija: s/confusion/conclusion/.  ha ha.

**Comment by dhruvdhody** [comment]
Here is a draft text, feel free to use or reword it as you see fit! 
````
As new technologies (and related standards) are developed and deployed, 
it can be surprising to see their unintended consequences. While making 
decisions on technology direction, it is important to factor in its impact on 
all kinds of network deployments and their unique requirements. There could 
be trade-offs, which need careful examination and conceivably look out for 
alternate means of achieving the desired goals. If they cannot be, these 
choices and reasoning ought to be thoroughly documented. 
````
